# Generated by Django 6.0.4 on 2026-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('atentido', models.BooleanField(default=False)),
                ('horario', models.DateTimeField()),
            ],
        ),
    ]
