# Generated by Django 6.0.4 on 2026-04-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='atentido',
            new_name='atendido',
        ),
    ]
