# Generated by Django 6.0.4 on 2026-06-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_agendamento_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
