# Generated by Django 6.0.4 on 2026-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_agendamento_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
