# Generated by Django 6.0.4 on 2026-07-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('FALTOU', 'Faltou')], default='PENDENTE', max_length=15),
        ),
    ]
