# Generated by Django 6.0.4 on 2026-08-27 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_alter_agendamento_servico'),
        ('cliente', '0003_clienteprofissional_ativo_and_more'),
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='atendido',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='user',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_fim',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_inicio',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agendamento.agendamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_agendamento', to='servicos.servico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agendamento', 'servico'), name='servico_unico_por_agendamento')],
            },
        ),
    ]
