# Generated by Django 6.0.4 on 2026-08-21 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('public', '0005_alter_profile_horario_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_profissionais', to='cliente.cliente')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.profile')),
            ],
        ),
    ]
