# Generated by Django 6.0.4 on 2026-08-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_clienteprofissional'),
        ('public', '0005_alter_profile_horario_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofissional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clienteprofissional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteprofissional',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_clientes', to='public.profile'),
        ),
        migrations.AddConstraint(
            model_name='clienteprofissional',
            constraint=models.UniqueConstraint(fields=('cliente', 'profile'), name='cliente_profissional_unico'),
        ),
    ]
