# Generated by Django 6.0.4 on 2026-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nome_negocio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
