# Generated by Django 6.0.4 on 2026-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_profile_telefone_alter_profile_nome_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
