# Generated by Django 6.0.4 on 2026-08-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_profile_public_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='dias_funcionando',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='fim_almoco',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='inicio_almoco',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
