# Generated by Django 6.0.4 on 2026-08-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_profile_descricao_profile_dias_funcionando_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
